class TweetFields:
    Attachments = 'attachments'
    AuthorId = 'author_id'
    ContextAnnotations = 'context_annotations'
    ConversationId = 'conversation_id'
    CreatedAt = 'created_at'
    EditControls = 'edit_controls'
    Entities = 'entities'
    GEO = 'geo'
    Id = 'id'
    InReplyToUserId = 'in_reply_to_user_id'
    Lang = 'lang'
    NonePublicMetrics = 'non_public_metrics'
    PublicMetrics = 'public_metrics'
    OrganicMetrics = 'organic_metrics'
    PromotedMetrics = 'promoted_metrics'
    PossiblySensitive = 'possibly_sensitive'
    ReferencedTweets = 'referenced_tweets'
    ReplySettings = 'reply_settings'
    Source = 'source'
    Text = 'text'
    Withheld = 'withheld'


class UserFields:
    CreatedAt = 'created_at'
    Description = 'description'
    Entities = 'entities'
    Id = 'id'
    Location = 'location'
    Name = 'Name'
    PinnedTweetId = 'pinned_tweet_id'
    ProfileImageURL = 'profile_image_url'
    Protected = 'protected'
    PublicMetrics = 'public_metrics'
    URL = 'url'
    Username = 'username'
    Verified = 'verified'
    VerifiedType = 'verified_type'
    Withheld = 'withheld'
